#!/usr/bin/env python

import sys
import re
from publish.importing import _read_file as read_file
from django.template import Template, Context
from django.conf import settings as django_settings

if len(sys.argv) != 2:
    print "Correct usage ./custom-styling foo.template"
    sys.exit(2)
else:
    # Read template
    django_settings.configure(INSTALLED_APPS='/Users/hnarayan/Projects/publish/contrib/harish')
    template_file_name = sys.argv[1]
    template_file      = open(template_file_name)
    template           = Template(template_file.read())

    # Read data
    papers = read_file("papers.pub")

    # Output results
    context = Context({"papers": papers})
    output = template.render(context)
#   Filters for HTML
#    output = re.sub('--', '&#8211;', output)
#    output = re.sub('DOC_ROOT', '<!--#echo var="MY_DOCUMENT_ROOT"-->', output)
#   Filters for LaTeX
    print output
    
