#!/usr/bin/env python

import sys
from publish.importing import _read_file as read_file
from django.template import Template, Context
from django.conf import settings as django_settings

if len(sys.argv) != 2:
    print "Correct usage ./custom-styling foo.template"
    sys.exit(2)
else:
    # Read template
    django_settings.configure()
    template_file_name = sys.argv[1]
    template_file      = open(template_file_name)
    template           = Template(template_file.read())

    # Read data
    papers = read_file("papers.pub")

    # Output results
    for paper in papers:
        context = Context(paper)
        print template.render(context)
