"This module defines a list of known journal names, abbreviations and issn-numbers."

__author__ = "Anna Logg (anna@loggsystems.se)"
__date__ = "2008-10-23 -- 2008-10-29"
__copyright__ = "Copyright (C) 2008 Anna Logg"
__license__  = "GNU GPL version 3 or any later version"

journals = [("none", "none", "xxxx-xxxx"),
            ("ACM Trans. Math. Software", "ACM Transactions on Mathematical Software", "0098-3500"),
            ("ACM Comput. Surv.", "ACM Computing Surveys", "0360-0300"),
            ("ACM SIGSOFT Software Engineering Notes", "ACM SIGSOFT Software Engineering Notes", "01635848"),
            ("ACM Trans. Multimed. Comput. Comm. Appl.", "ACM Transactions on Multimedia Computing, Communications, and Applications", "1551-6857"),
            ("ACM Trans. Software Eng. Meth.", "ACM Transactions on Software Engineering and Methodology", "1049-331X"),
            ("Adv. Comput. Math.", "Advances in Computational Mathematics", "1019-7168"),
            ("Adv. Water Resour.", "Advances in Water Resources", "0309-1708"),
            ("Ann. Biomed. Eng.", "Annals of Biomedical Engineering", "0090-6964"),
            ("Appl. Cognit. Psychol.", "Applied Cognitive Psychology", "0888-4080"),
            ("Appl. Math. Comput.", "Applied Mathematics and Computation", "0096-3003"),
            ("Appl. Math. Finance", "Applied Mathematical Finance", "1350-486X"),
            ("Appl. Math. Model.", "Applied Mathematical Modelling", "0307-904X"),
            ("Appl. Mech. Eng.", "Applied Mechanics and Engineering", "1425-1655"),
            ("Behaviour \\& Information Technology", "Behaviour \\& Information Technology", "0144-929X"),
            ("Biophys. J.", "Biophysical Journal", "0006-3495"),
            ("BIT", "BIT Numerical Mathematics", "0006-3835"),
            ("Camput-Wide Information Systems", "Campus-Wide Information Systems", "1065-0741"),
            ("Comput. Biol. Med.", "Computers in Biology and Medicine", "0010-4825"),
            ("Comput. Comm.", "Computer Communications", "0140-3664"),
            ("Comput. Geosci.", "Computational Geosciences", "1420-0597"),
            ("Comput. Phys.", "Communications in Computational Physics", "1814-2406"),
            ("Comput. Math. Appl.", "Computers \\& Mathematics with Applications", "0898-1221"),
            ("Comput. Mech.", "Computational Mechanics. Solids, Fluids, Engineered Material, Aging Infrastructure, Molecular Dynamics, Heat Transfer, Manufacturing Processes, Optimization, Fracture \& Integrity", "0178-7675"),
            ("Comput. Methods Appl. Mech. Engrg", "Computer Methods in Applied Mechanics and Engineering", "0045-7825"),
            ("Comput. Meth. Biomech. Biomed. Eng.", "Computer Methods in Biomechanics and Biomedical Engineering", "1025-5842"),
            ("Comput. Sci. Eng.", "Computing in Science \\& Engineering", "1521-9615"),
            ("Comput. Vis. Sci.", "Computing and Visualization in Science", "1432-9360"),
            ("Continent. Shelf Res.", "Continental Shelf Research", "0278-4343"),
            ("Empir. Software Eng.", "Empirical Software Engineering", "1382-3256"),
            ("Eng. Anal. Bound. Elem.", "Engineering Analysis with Boundary Elements", "0955-7997"),
            ("Formal Aspect. Comput.", "Formal Aspects of Computing", "0934-5043"),
            ("Future Generat. Comput. Syst.", "Future Generation Computer Systems", "0167-739X"),
            ("Global J. Pure Appl. Math.", "Global Journal of Pure and Applied Mathematics", "0973-1768"),
            ("IEEE/ACM Transactions on Networking", "IEEE/ACM Transactions on Networking", "1063-6692"),
            ("IEEE Comm. Lett.", "IEEE Communications Letters", "1089-7798"),
            ("IEEE Comm. Mag.", "IEEE Communications Magazine", "0163-6804"),
            ("IEEE Comput. Appl. Power Mag.", "IEEE Computer Applications in Power Magazine", "0895-0156"),
            ("IEEE Comput. Architect. Lett.", "IEEE Computer Architecture Letters", "1556-6056"),
            ("IEEE Control Syst. Mag.", "IEEE Control Systems Magazine", "1066-033X"),
            ("IEEE Distr. Syst. Online", "IEEE Distributed Systems Online", "1541-4922"),
            ("IEEE Micro Magazine", "IEEE Micro Magazine", "0272-1732"),
            ("IEEE Netw. Mag. Global Inform. Exchange", "IEEE Network: The Magazine of Global Information Exchange", "0890-8044"),
            ("IEEE Software Mag.", "IEEE Software Magazine", "0740-7459"),
            ("IEEE Trans. Biomed. Eng.", "IEEE Transactions on Biomedical Engineering", "0018-9294"),
            ("IEEE Trans. Comput.", "IEEE Transactions on Computers", "0018-9340"),
            ("IEEE Transactions on Industrial Informatics", "IEEE Transactions on Industrial Informatics", "1551-3203"),
            ("IEEE Trans. Parallel Distr. Syst.", "IEEE Transactions on Parallel and Distributed Systems", "1045-9219"),
            ("IEEE Trans. Software Eng.", "IEEE Transactions on Software Engineering", "0098-5589"),
            ("IEEE Trans. Wireless Comm.", "IEEE Transactions on Wireless Communications", "1536-1276"),
            ("IET Communications", "IET Communications", "1751-8628"),
            ("IMA J. Appl. Math.", "IMA Journal of Applied Mathematics", "0272-4960"),
            ("IMA J. Numer. Anal.", "IMA Journal of Numerical Analysis", "0272-4979"),
            ("Inform. Process. Lett.", "Information Processing Letters", "0020-0190"),
            ("Inform. Software Tech.", "Information and Software Technology", "0950-5849"),
            ("ISA Transactions", "ISA Transactions", "0019-0578"),
            ("Appl. Mech. Eng.", "International Journal of Applied Mechanics and Engineering", "1425-1655"),
            ("J. Comput. Methods Eng. Sci. Mech.", "International Journal for Computational Methods in Engineering Science and Mechanics", "1550-2287"),
            ("International Journal of Autonomous and Adaptive Communications Systems", "International Journal of Autonomous and Adaptive Communications Systems", "1754-8632"),
            ("International Journal of Bioelectromagnetism", "International Journal of Bioelectromagnetism", "1456-7857"),
            ("Int. J. Comput. Eng. Sci.", "International Journal of Computational Engineering Science", "1465-8763"),
            ("Int. J. Comput. Math.", "International Journal of Computer Mathematics", "0020-7160"),
            ("Int. J. Forecast", "International Journal of Forecasting", "0169-2070"),
            ("Int. J. Fluid Mech. Res.", "International Journal of Fluid Mechanics Research", "1064-2277"),
            ("Int. J. Numer. Anal. Model.", "International Journal of Numerical Analysis and Modeling", "1705-5105"),
            ("Int. J. Nonlinear Sci. Numer. Simul.", "International Journal of Nonlinear Sciences and Numerical Simulation", "1565-1339"),
            ("Int. J. Nonlinear Model. Sci. Eng.", "International Journal of Nonlinear Modelling in Science and Engineering", "1472-085X"),
            ("Int. J. Numer. Meth. Eng.", "International Journal for Numerical Methods in Engineering", "0029-5981"),
            ("Int. J. Numer. Meth. Fluid.", "International Journal for Numerical Methods in Fluids", "0271-2091"),
            ("Int. J. Proj. Manag.", "International Journal of Project Management", "0263-7863"),
            ("International Journal of Pure and Applied Mathematics", "International Journal of Pure and Applied Mathematics", "1311-8080"),
            ("Int. J. Software Eng. Knowl. Eng.", "International Journal of Software Engineering and Knowledge Engineering", "0218-1940"),
            ("J. Comput. Acoust", "Journal of Computational Acoustics", "0218-396X"),
            ("J. Comput. Appl. Math.", "Journal of Computational and Applied Mathematics", "0377-0427"),
            ("J. Comput. Finance", "Journal of Computational Finance", "1460-1559"),
            ("J. Comput. Neurosci.", "Journal of Computational Neuroscience", "0929-5313"),
            ("J. Comput. Phys.", "Journal of Computational Physics", "0021-9991"),
            ("Journal d'Analyse Mathematique", "Journal d'Analyse Mathematique", "0021-7670"),
            ("J. Geodyn.", "Journal of Geodynamics", "0264-3707"),
            ("J. Geophys. Res. B", "Journal of Geophysical Research (JGR)-B", "0196-6936"),
            ("Journal of Medical Ultrasonics", "Journal of Medical Ultrasonics", "1346-4523"),
            ("J. Netw. Comput. Appl.", "Journal of Network and Computer Applications", "1084-8045"),
            ("J. Numer. Math.", "Journal of Numerical Mathematics", "1570-2820"),
            ("J. Object Tech.", "Journal of Object Technology", "1660-1769"),
            ("J. Sci. Comput.", "Journal of Scientific Computing", "0885-7474"),
            ("J. Software Mainten. Evol. Res. Pract.", "Journal of Software Maintenance and Evolution: Research and Practice", "1532-060X"),
            ("J. Stat. Software", "Journal of Statistical Software", "1548-7660"),
            ("J. Syst. Architect.", "Journal of Systems Architecture", "1383-7621"),
            ("J. Syst. Software", "Journal of Systems and Software", "0164-1212"),
            ("Math. Biosci.", "Mathematical Biosciences", "0025-5564"),
            ("Math. Comp.", "Mathematics of Computation", "0025-5718"),
            ("Math. Comput. Simulat.", "Mathematics and Computers in Simulation", "0378-4754"),
            ("Math. Geol.", "Mathematical Geology", "0882-8121"),
            ("Metheoritics Planet. Sci.", "Metheoritics \\& Planetary Science", "1086-9379"),
            ("Mobile Network. Appl.", "Mobile Networks and Applications", "1383-469X"),
            ("Model. Identif. Control", "Modeling, Identification and Control. A Norwegian Research Bulletin", "0332-7353"),
            ("Multi Agent and Grid Systems", "Multi Agent and Grid Systems", "1574-1702"),
            ("Nord. J. Comput.", "Nordic Journal of Computing", "1236-6064"),
            ("Norwegian Journal of Geography/ Norsk Geografisk Tidsskrift", "Norwegian Journal of Geography/ Norsk Geografisk Tidsskrift", "0029-1951"),
            ("Numer. Linear Algebra Appl.", "Numerical Linear Algebra with Applications", "1070-5325"),
            ("Numer. Methods Partial Differential Equations", "Numerical Methods for Partial Differential Equations. An International Journal", "0749-159X"),
            ("Numer. Math.", "Numerische Mathematik", "0029-599X"),
            ("Otic. Comm.", "Optics Communications", "0030-4018"),
            ("Perform. Eval.", "Performance Evaluation", "0166-5316"),
            ("Personal and Ubiquitous Computing", "Personal and Ubiquitous Computing", "1617-4909"),
            ("Phys. Earth Planet. In.", "Physics of the Earth and Planetary Interiors", "0031-9201"),
            ("Phys. Rev. B Condens. Matter", "Physical Review B: Condensed Matter and Materials Physics", "1098-0121"),
            ("Proc. IEEE Comput. Soc. Bioinformatics Conf. IEEE Comput. Soc. Bioinformatic", "Proceedings / IEEE Computer Society Bioinformatics Conference. IEEE Computer Society Bioinformatics Conference", "1555-3930"),
            ("Research Letters in Communications", "Research Letters in Communications", "1687-6741"),
            ("Scand. J. Inform. Syst.", "Scandinavian Journal of Information Systems", "0905-0167"),
            ("Sci. Program.", "Scientific Programming", "1058-9244"),
            ("SIAM J. Numer. Anal.", "SIAM Journal on Numerical Analysis", "0036-1429"),
            ("SIAM J. Sci. Comput.", "SIAM Journal on Scientific Computing", "1064-8275"),
            ("Software Process Improv. Pract.", "Software Process: Improvement and Practice", "1077-4866"),
            ("Software Syst. Model.", "Software and Systems Modeling", "1619-1366"),
            ("Stroke", "Stroke", "0039-2499"),
            ("Transactions on Machine Learning and Data Mining", "Transactions on Machine Learning and Data Mining", "1865-6781"),
            ("Transp. Porous Media", "Transport in Porous Media", "0169-3913"),
            ("Wireless Pers. Comm.", "Wireless Personal Communications", "0929-6212")]
